name: ui_gen_demo
description: "Generative UI demo app using Flutter"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.5.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.2
  llm_json_stream: ^0.2.1
  provider: ^6.1.5+1
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
